---

  - name: Disable password authentication in SSH
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PasswordAuthentication'
      line: 'PasswordAuthentication no'
      state: present
    notify: Restart SSH Service
      
  - name: Enable public key authentication
    ansible.builtin.lineinfile:
      path: /etc/ssh/sshd_config
      regexp: '^PubkeyAuthentication'
      line: 'PubkeyAuthentication yes'
      state: present
    notify: Restart SSH Service
