---
- name: Create a users with root privileges
  tags: access
  block:
    - name: Import task to grant access to user
      ansible.builtin.import_tasks: access_user_management.yml
    - name: Import task to edit sshd_config file
      ansible.builtin.import_tasks: access_sshd_config.yml 
